services:
  - type: web
    name: agricultural-health-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn simple_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
